Main:
  prefix: '&6Luser&bRealms &c|'
  debug: true
  updater: true
  backup-interval: 1800 #seconds
  log-save-interval: 120 #seconds
  load-max-ms-per-tick: 10
  save-max-ms-per-tick: 10

  world-blacklist:
    - 'someworld'

  # scarecrow will scare insects away from crops.
  scarecrow:
    enabled: true

  # vermin will eat crops and make them grow slower.
  insects:
    enabled: true

  # bees that around pots will pollinate crops and make them grow faster.
  bees:
    enabled: true
    radius: 8 # radius between bee and crop
    chance: 0.5
    check-interval: 500 # ticks
    particle:
      type: 'REDSTONE'
      count: 1
      color: 'GREEN'
      color-size: 1
      offset:
        x: 0.5
        y: 0.5
        z: 0.5

  schedule:
    enabled: true
    time: '07:00' # every day at 07:00 pots sprinklers will water them, and crops will grow, after that pots will be dry.

  seasons:
    enabled: true
    list: # you can add more seasons.
      spring:
        enabled: true
        name: '&aİlkbahar'
        time: 144 # minecraft days
        order: 1 # order of seasons
      summer:
        enabled: true
        name: '&eYaz'
        time: 144 # minecraft days
        order: 2 # order of seasons
      autumn:
        enabled: true
        name: '&6Sonbahar'
        time: 144 # minecraft days
        order: 3 # order of seasons
      winter:
        enabled: true
        name: '&bKış'
        time: 144 # minecraft days
        order: 4 # order of seasons

  greenhouse:
    enabled: true

Data:
  provider: 'yaml' # yaml, mysql, sqlite
  ip: 'localhost'
  port: '3306'
  database: 'db_name'
  username: 'root'
  password: 'myawsomerootpass'

Hooks:
  placeholderapi: true
  itemsadder: false
  mythicmobs: false

Time:
  second: 'saniye'
  minute: 'dakika'
  hour: 'saat'
  day: 'gün'
  week: 'hafta'
  month: 'ay'
  year: 'yıl'

Numbers:
  decimal: true # 281.123...
  formats:
    enabled: true
    thousand: "K"
    million: "M"
    billion: "B"
    trillion: "T"
    quadrillion: "Q"

Sound:
  success: 'ENTITY_PLAYER_LEVELUP'
  fail: 'ENTITY_VILLAGER_HURT'
  reload: 'ENTITY_PLAYER_LEVELUP'
